site_name: Документация

theme:
  name: material

nav:
  - Home: 'index.md'
  - lr_1:
      - Task_1: 'lr_1/task_1.md'
      - Task_2: 'lr_1/task_2.md'
      - Task_3: 'lr_1/task_3.md'
      - Task_4: 'lr_1/task_4.md'
      - Task_5: 'lr_1/task_5.md'
  - lr_2:
      - User: 'lr_2/user.md'
      - Homework: 'lr_2/homework.md'
  - lr_3:
      - lr_3.1:
          - Prac_1: 'lr_3/lr_3_1/prac_1.md'
          - Prac_2: 'lr_3/lr_3_1/prac_2.md'
          - Prac_3: 'lr_3/lr_3_1/prac_3.md'
      - lr_3.2:
          - Climbers: 'lr_3_2/climbers.md'
          - Mentors: 'lr_3_2/mentors.md'
          - Mountains: 'lr_3_2/mountains.md'
          - Routes: 'lr_3_2/routes.md'
          - Clubs: 'lr_3_2/clubs.md'
          - Climbs: 'lr_3_2/climbs.md'
          - Groups: 'lr_3_2/groups.md'
          - Group Members: 'lr_3_2/group_members.md'
  - lr_4:
      - Login: 'lr_4/views/login.md'
      - Register: 'lr_4/views/register.md'
      - Mount: 'lr_4/views/mount.md'
      - Register: 'lr_4/views/register.md'
      - Routes: 'lr_4/views/routes.md'